# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en
pipeline:
  # - name: ConveRTTokenizer
  #   "case_sensitive": False
  #   "model_url": "https://github.com/PolyAI-LDN/polyai-models/releases/download/v1.0/model.tar.gz"
  # - name: ConveRTFeaturizer
  #   "model_url": "https://github.com/PolyAI-LDN/polyai-models/releases/download/v1.0/model.tar.gz"
  - name: SpacyNLP
  - name: SpacyTokenizer
  - name: SpacyFeaturizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
    OOV_token: oov
    token_pattern: (?u)\b\w+\b
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 200
  - name: custom_components.regex2.RegexEntityExtractor
  - name: EntitySynonymMapper
  - name: ResponseSelector
    retrieval_intent: smalltalk
    epochs: 200
    scale_loss: false
# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies: 
  - name: TEDPolicy
    max_history: 10
    epochs: 20
    batch_size:
    - 32
    - 64
  - name: AugmentedMemoizationPolicy
    max_history: 6
  - name: FormPolicy 
  - name: MappingPolicy